### ISSUE TITLE
Keyboard crashes

### ISSUE THREAD

**Issue by ghost** [bhbr/MQKB#28]
IPhone 7 plus
iOS version: 10.3.3

Steps to duplicate: 
1. Hold letter 'a' to reveal the alphabet.
2. Drag finger to any letter in the top row (qwertyuiop)
3. Keyboard crashes and all previous input is lost.

If your finger motion is slow and deliberate,  stopping briefly at each letter along the way, you can use variables in the top row. Otherwise, the keyboard crashes.

**Comment by bhbr** [comment]
OK, I think I fixed it. There were some performance issues because each letter was drawn as a UILabel, but I found a more lightweight solution.
I'll leave the issue open until the next beta version, let me know here if the issue persists.

**Comment by bhbr** [comment]
Ok, NOW I think I fixed it. Turns out not the UILabels were the problem, but the fact that I recreated 26 of them each time a new letter got highlighted while dragging. Ahem. That this bug appears neither in simulator mode nor in debugging mode, nor in Instruments, did not help.

Please tell me whether the problem persists in version 0.4.

**Comment by ghost** [comment]
I have version 0.4 installed but there is still a problem with the keyboard crashing. It isn't the same though and I'll try to narrow down the exact behavior that causes the crash over the weekend. I'm unable to completely enter a formula without a crash, and it appears to be tied to the symbols. The letters are working just fine now and I can scroll over them quickly and add multiple without a crash.
